export const SUPABASE_URL = "https://jduumpdgpivanpylnbdb.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkdXVtcGRncGl2YW5weWxuYmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MjIzODYsImV4cCI6MjA3OTE5ODM4Nn0.qtzKKKc0VDOC0LlW-Xx-zRLccUF2bXNFydDrzZ6H_dE";


